name: Markdown Lint and Spell Check

on:
  pull_request:
    branches:
      - main

jobs:
  markdown-check:
    name: Run markdownlint and cspell
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install markdownlint and cspell
        run: |
          npm install -g markdownlint-cli2 cspell

      - name: Run markdownlint
        run: |
          markdownlint-cli2 "**/*.md" "#node_modules"

      - name: Run spell check
        run: |
          cspell "**/*.md"
